// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8N8rhjE-S1K4ajHqek49NEUM2czlOHyQ',
    appId: '1:593592273123:web:2562ab67c73c6854641dd6',
    messagingSenderId: '593592273123',
    projectId: 'project2-a6616',
    authDomain: 'project2-a6616.firebaseapp.com',
    storageBucket: 'project2-a6616.firebasestorage.app',
    measurementId: 'G-K41DBMWX3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeiEU39pmDUARKKDYtsh5Sl0-uofbHrUE',
    appId: '1:593592273123:android:96d40aa813fcf404641dd6',
    messagingSenderId: '593592273123',
    projectId: 'project2-a6616',
    storageBucket: 'project2-a6616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlfw0FvWKAptWcZw0fNz4Kn9Qk7xEfZgs',
    appId: '1:593592273123:ios:85a1d16cbe06b83c641dd6',
    messagingSenderId: '593592273123',
    projectId: 'project2-a6616',
    storageBucket: 'project2-a6616.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlfw0FvWKAptWcZw0fNz4Kn9Qk7xEfZgs',
    appId: '1:593592273123:ios:85a1d16cbe06b83c641dd6',
    messagingSenderId: '593592273123',
    projectId: 'project2-a6616',
    storageBucket: 'project2-a6616.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8N8rhjE-S1K4ajHqek49NEUM2czlOHyQ',
    appId: '1:593592273123:web:89ff89371265d9f3641dd6',
    messagingSenderId: '593592273123',
    projectId: 'project2-a6616',
    authDomain: 'project2-a6616.firebaseapp.com',
    storageBucket: 'project2-a6616.firebasestorage.app',
    measurementId: 'G-YM3L70XTJE',
  );
}
